name: Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Library:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dc: [ dmd-latest, ldc-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

    - name: 'Test'
      run: |
        dub test --compiler=$DC
  Client:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dc: [ dmd-latest, ldc-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

    - name: 'Build'
      run: |
        dub build :client --compiler=$DC
